work_dir: ./work_dir/recognition/tst-xsub/ST_GCN
weights: ./models/st_gcn.ntu-xsub.pt
ignore_weights: ['fcn.weight', 'fcn.bias']
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/tst_fall_detection/xsub/train_data.npy
  label_path: ./data/tst_fall_detection/xsub/train_label.pkl
test_feeder_args:
  data_path: ./data/tst_fall_detection/xsub/val_data.npy
  label_path: ./data/tst_fall_detection/xsub/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 2
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 4
test_batch_size: 4
num_epoch: 10



